Support pkce part 3
Cloud-Foundations/keymaster pull request #106
Opened 2021-03-27 00:21 UTC by cviecco

2021-03-31 17:40 UTC, rgooch requested changes

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc.go
> +func (state *RuntimeState) idpOpenIDCClientCanDoPKCEAuth(client_id string) (bool, error) {
s/client_id/clientId/

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc.go
> +			// Did not had this mandatory, however given the need for password
s/had/have/
s/this/this as/

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc_test.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc_test.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc_test.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc_test.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc_test.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc_test.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc_test.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc_test.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc_test.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc_test.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc_test.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc_test.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc_test.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc_test.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc_test.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc_test.go
> +
Please remove blank line.

2021-03-31 17:40 UTC, rgooch commented on cmd/keymasterd/idp_oidc_test.go
Please remove blank line.

2021-04-05 22:01 UTC, cviecco commented on cmd/keymasterd/idp_oidc.go
> +			state.writeFailureResponse(w, r, http.StatusBadRequest, "Options MUST contain origin")
Good catch.

2021-04-08 16:43 UTC, merged