Fix client no retry on good token
Cloud-Foundations/keymaster pull request #171
Opened 2022-06-17 15:31 UTC by cviecco

1. The okta 2fa cope did not return an error message when no valid autneticators where available
2. When both mfa AND token failed the client did not termiate on error conditins

2022-08-18 22:19 UTC, rgooch requested changes

2022-08-18 22:19 UTC, rgooch commented on cmd/keymaster/main.go
> +	logger.Debugf(1, "SetupCerts: authenticaiton Complete")
s/authenticaiton/authentication/

2022-08-18 22:19 UTC, rgooch commented on cmd/keymasterd/2fa_okta.go
> +		logger.Debugf(2, "oktaPushStartHandler: usedata for broken user%s is :%s", authData.Username, userResponse)
s/usedata/userdata/ ?

2022-08-18 22:19 UTC, rgooch commented on lib/authenticators/okta/impl.go
> +	pa.logger.Debugf(2, "oktaAuthenticator: validsteUserPush: after getting userResponse=%+v", userResponse)
`validste`?

2024-06-15 16:57 UTC, rgooch commented
Is this PR still needed? Review comments are still open.

2024-06-23 16:38 UTC, cviecco commented
Closed with new revision reopened

2024-06-23 16:38 UTC, closed without merging

2024-06-23 16:47 UTC, rgooch commented
Changes in PR #240.