Trying with device loops and checks
Cloud-Foundations/keymaster pull request #198
Opened 2023-06-09 21:57 UTC by cviecco

2023-06-10 05:11 UTC, rgooch commented
Will this be easier to review if https://github.com/Cloud-Foundations/keymaster/pull/197#pullrequestreview-1473312455 is merged?

2023-06-18 18:06 UTC, rgooch requested changes

2023-06-18 18:06 UTC, rgooch commented on lib/client/twofa/u2f/u2f_test.go
> +				t.Fatalf("Falied to INvalidate valid appId for base=%s, appid=%s", baseURL, appId)
s/IN/in/

2023-06-19 16:29 UTC, cviecco commented on lib/client/twofa/u2f/u2f.go
> +				logger.Debugf(1, "device.Authenticate retured non error %s", err)
done

2023-06-19 16:29 UTC, cviecco commented on lib/client/twofa/u2f/u2f.go
> +			case "Device is requesting test of use presence to fulfill the request.":
changed this for a variable that refers to the upstream code library so that we dont have magic strings. Same witht he one blow

2023-06-19 16:31 UTC, cviecco commented on lib/client/twofa/u2f/u2f.go
> +					if req.WebAuthn == true {
done

2023-06-19 16:32 UTC, cviecco commented on lib/client/twofa/u2f/u2f.go
> +						// Depending how some devices u2f devices we registerd we need
done

2023-06-19 16:32 UTC, cviecco commented on lib/client/twofa/u2f/u2f.go
> +				} else if err.Error() == "Device is requesting test of use presence to fulfill the request." && !prompted {
done with the adding of new variables.

2023-06-19 16:45 UTC, cviecco commented on lib/client/twofa/u2f/u2f_test.go
> +				t.Fatalf("Falied to INvalidate valid appId for base=%s, appid=%s", baseURL, appId)
done

2023-06-20 07:33 UTC, rgooch approved these changes

2023-06-20 17:53 UTC, merged