Add sshcert auth
Cloud-Foundations/keymaster pull request #245
Opened 2024-10-17 19:54 UTC by cviecco

2024-10-18 20:29 UTC, rgooch requested changes

2024-10-18 20:29 UTC, rgooch commented on cmd/keymasterd/app.go
> +	"github.com/cviecco/webauth-sshcert/lib/server/sshcertauth"
:cry:

2024-10-18 20:29 UTC, rgooch commented on cmd/keymasterd/app.go
> +	// TODO: only enable these handlers if sshcertauth is enabled
When will this be done?

2024-10-18 20:29 UTC, rgooch commented on cmd/keymasterd/auth_sshcert.go
> +// Thus function can only be called after all known keymaster public keys
s/Thus/This/

2024-10-18 20:29 UTC, rgooch commented on cmd/keymasterd/auth_sshcert.go
> +	username, maxAge, userErrString, err := s.sshCertAuthenticator.LoginWithChallenge(r)
s/maxAge/expiration/
Apply throughout function.

2024-10-21 22:48 UTC, cviecco commented on cmd/keymasterd/app.go
> +	// TODO: only enable these handlers if sshcertauth is enabled
done

2024-10-25 04:32 UTC, rgooch requested changes

2024-10-25 04:32 UTC, rgooch commented on cmd/keymasterd/auth_sshcert.go
> +// Thus function can only be called after all known keymaster public keys
Ping?

2024-10-25 04:32 UTC, rgooch commented on cmd/keymasterd/auth_sshcert.go
> +	username, maxAge, userErrString, err := s.sshCertAuthenticator.LoginWithChallenge(r)
Ping?

2024-10-26 22:00 UTC, cviecco commented on cmd/keymasterd/auth_sshcert.go
> +// Thus function can only be called after all known keymaster public keys
done

2024-10-27 20:33 UTC, rgooch approved these changes

2024-10-28 15:23 UTC, merged