Adding ed25519 parallel signer
Cloud-Foundations/keymaster pull request #99
Opened 2021-03-12 17:09 UTC by cviecco

2021-03-18 16:28 UTC, rgooch requested changes

2021-03-18 16:28 UTC, rgooch commented on cmd/keymasterd/config.go
> +			return fmt.Errorf("signer content is not pem encoded or armor decocable")
s/decocable/decodable/

2021-03-18 16:28 UTC, rgooch commented on cmd/keymasterd/unseal.go
> -		return fmt.Errorf("cannot generate CA DER: %s", err)
Error is ignored?

2021-03-18 16:28 UTC, rgooch commented on cmd/keymasterd/unseal.go
> +	// TODO.. make network error blocks to goroutines
s/make/move/ ?

2021-03-18 16:28 UTC, rgooch commented on cmd/keymasterd/unseal.go
>  	}
Error is ignored?

2021-03-22 15:17 UTC, cviecco commented on cmd/keymasterd/unseal.go
>  	}
fixed

2021-03-22 17:09 UTC, rgooch commented on cmd/keymasterd/config.go
> +			return fmt.Errorf("signer content is not pem encoded or armor decocable")
I don't see this fixed?

2021-03-22 23:51 UTC, merged